# This file provides instructions for packaging.

@prefix : <http://ontologi.es/doap-deps#>.

`Exporter-LexicalVars`
	:runtime-requirement    [ :on "perl 5.008003"^^:CpanId ];
	:runtime-requirement    [ :on "B::Hooks::Parser"^^:CpanId ];
	:runtime-requirement    [ :on "Exporter::Shiny"^^:CpanId ];
	:test-requirement       [ :on "Test::More 0.96"^^:CpanId ];
	:develop-recommendation [ :on "Dist::Inkt 0.001"^^:CpanId ];
	.

